name: CI Kronicle Metadata

on: push

jobs:

  ci-kronicle-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 11 🏗
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper 👀
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4

      - name: Validate kronicle.yaml 👀
        run: ./gradlew validateKronicleMetadata
